export const NONE_ROUTE_MASK = 1<<0;
export const ADMIN_ROUTE_MASK = 1<<1;
export const OPERATE_MANAGE_ROUTE_MASK = 1<<2;
export const OPERATE_ROUTE_MASK = 1<<3;
export const IDEA_MANAGE_ROUTE_MASK = 1<<4;
export const IDEA_DIRECTOR_ROUTE_MASK = 1<<5;
export const IDEA_PHOTOGRAPHY_ROUTE_MASK = 1<<6;
export const IDEA_MONTAGE_ROUTE_MASK = 1<<7;
export const IDEA_DESIGN_ROUTE_MASK = 1<<8;
export const FINANCE_ROUTE_MASK = 1<<9;

export const ALL_ROUTE_MASK = (1<<23) - 1;
export const EXCLUDE_FINANCE_ROUTE_MASK = ALL_ROUTE_MASK ^ FINANCE_ROUTE_MASK;// 全部路由中排除掉财务
export const MANAGERS_ROUTE_MASK = ADMIN_ROUTE_MASK | OPERATE_MANAGE_ROUTE_MASK | IDEA_MANAGE_ROUTE_MASK;
export const FINANCE_CENTER_ROUTE_MASK = ADMIN_ROUTE_MASK | FINANCE_ROUTE_MASK;
export const IDEA_INTERGRATED_MASK = IDEA_MANAGE_ROUTE_MASK | IDEA_DIRECTOR_ROUTE_MASK | IDEA_PHOTOGRAPHY_ROUTE_MASK | IDEA_MONTAGE_ROUTE_MASK | IDEA_DESIGN_ROUTE_MASK;// 所有创意
export const IDEA_MEMBER_MASK = IDEA_DIRECTOR_ROUTE_MASK | IDEA_PHOTOGRAPHY_ROUTE_MASK | IDEA_MONTAGE_ROUTE_MASK | IDEA_DESIGN_ROUTE_MASK;// 普通创意
export const OPERATE_INTERGRATED_MASK = OPERATE_MANAGE_ROUTE_MASK | OPERATE_ROUTE_MASK;// 所有运营

export const ROUTE_MASK_LIST = {
    1: ADMIN_ROUTE_MASK,
    21: OPERATE_MANAGE_ROUTE_MASK,
    22: OPERATE_ROUTE_MASK,
    31: IDEA_MANAGE_ROUTE_MASK,
    321: IDEA_DIRECTOR_ROUTE_MASK,
    322: IDEA_PHOTOGRAPHY_ROUTE_MASK,
    323: IDEA_MONTAGE_ROUTE_MASK,
    324: IDEA_DESIGN_ROUTE_MASK,
    41: FINANCE_ROUTE_MASK,
    42: FINANCE_ROUTE_MASK,
    0: NONE_ROUTE_MASK
};

/**
 * @param id
 * @returns {*} Number
 */
export function GetUserRouteMask(id) {
    return ROUTE_MASK_LIST[id];
}

export function GetRole(roleId) {
    return roleId.reduce((res,item)=>res*10+Number(item),0);
}